### ISSUE TITLE
mutant-rspec not working out of the box

### ISSUE THREAD

**Issue by lnussbaum** [mbj/mutant#714]
I had trouble getting mutant-rspec to work on ruby 2.3.3.
I got this:
```
$ mutant --use rspec [...]
Could not load integration "rspec" (you may want to try installing the gem mutant-rspec)
```

The mutant-rspec gem was installed.

I did not understand the issue, but "fixed" it like that:
```
--- mutant-0.8.13/lib/mutant/integration.rb	2017-06-20 09:42:08.188521318 +0200
+++ /home/lucas/.gem/ruby/2.3.0/gems/mutant-0.8.13/lib/mutant/integration.rb	2017-06-08 00:20:00.415044246 +0200
@@ -1,3 +1,4 @@
+require 'mutant/integration/rspec'
 module Mutant
 
   # Abstract base class mutant test framework integrations
```

Then I ran into another issue:
```
$ mutant --use rspec [...]
/home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-rspec-0.8.13/lib/mutant/integration/rspec.rb:52:in `<class:Rspec>': undefined method `memoize' for Mutant::Integration::Rspec:Class (NoMethodError)
	from /home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-rspec-0.8.13/lib/mutant/integration/rspec.rb:23:in `<class:Integration>'
	from /home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-rspec-0.8.13/lib/mutant/integration/rspec.rb:5:in `<module:Mutant>'
	from /home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-rspec-0.8.13/lib/mutant/integration/rspec.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-0.8.13/lib/mutant/integration.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-0.8.13/lib/mutant.rb:179:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/lnussbaum/.gem/ruby/2.3.0/gems/mutant-0.8.13/bin/mutant:8:in `<top (required)>'
	from /home/lnussbaum/.gem/ruby/2.3.0/bin/mutant:22:in `load'
	from /home/lnussbaum/.gem/ruby/2.3.0/bin/mutant:22:in `<main>
```

Which I fixed by installing memoist, and adding:
```
diff -burN mutant-rspec-0.8.13/lib/mutant/integration/rspec.rb /home/lucas/.gem/ruby/2.3.0/gems/mutant-rspec-0.8.11/lib/mutant/integration/rspec.rb
--- mutant-rspec-0.8.13/lib/mutant/integration/rspec.rb	2017-06-20 09:44:00.438867302 +0200
+++ /home/lucas/.gem/ruby/2.3.0/gems/mutant-rspec-0.8.11/lib/mutant/integration/rspec.rb	2017-06-08 00:34:22.212373230 +0200
@@ -1,4 +1,5 @@
 require 'rspec/core'
+require 'memoist'
 
 module Mutant
   class Integration
@@ -20,6 +21,7 @@
     #
     # :reek:TooManyConstants
     class Rspec < self
+      extend Memoist
 
       ALL_EXPRESSION       = Expression::Namespace::Recursive.new(scope_name: nil)
       EXPRESSION_CANDIDATE = /\A([^ ]+)(?: )?/.freeze
```

**Comment by mbj** [comment]
@lnussbaum Does  `bundle exec mutant ...` fix this? Mutant is (intentionally) not designed to work without.

**Comment by lnussbaum** [comment]
it seems to work with bundle exec. My main motivation for using it outside bundler is that I would prefer not to add mutant to development dependencies, because I don't use it systematically.

**Comment by lnussbaum** [comment]
(also, none of the examples in the README mention bundle exec, so I didn't think of using it)

**Comment by mbj** [comment]
> it seems to work with bundle exec. My main motivation for using it outside bundler is that I would prefer not to add mutant to development dependencies, because I don't use it systematically.

I see this. But there is no way mutant can (without bundler) ensure by itself that all dependencies are present in non conflicting versions.

A `gem install mutant` followed by `mutant` is not guaranteed to ever work over time in a constantly changing gem environment.

Hence my preference to only ever support it inside bundler. I've to fix the README to always show `bundle exec` prefixed executions.

But I've no intend to support standalone execution, just for the fact I do not use it, and it would expose other users in a false sense of security.

I'll leave this issue open till I fixed the README.

**Comment by dgollahon** [comment]
@mbj Can this be closed in light of #731 / the current state of [the](https://github.com/mbj/mutant/blob/master/docs/mutant-rspec.md) [docs](https://github.com/mbj/mutant/blob/master/docs/mutant-minitest.md) or would you like me to add to the README mentioning an explicit requirement of using `bundle exec`?

**Comment by mbj** [comment]
@dgollahon I think that the mention of `bundle exec` is sufficient in the current integration docs.

Closing this. Good catch. Thanks.
